name: Create PR for release branch

on:
  push:
    tags:
      - 'prod-*'          # e.g. prod-v3.1.1

permissions:
  contents: read          # required by github-script
  pull-requests: write    # allow PR creation with GITHUB_TOKEN

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      # 1. Derive version from the tag name -------------------------------
      - name: Extract version number
        id: vars
        run: |
          tag="${GITHUB_REF#refs/tags/}"   # prod-v3.1.1
          version="${tag#prod-}"           # v3.1.1
          echo "version=$version" >>"$GITHUB_OUTPUT"

      # 2. Create (or find) the PR ----------------------------------------
      - name: Create pull request with GitHub API
        uses: actions/github-script@v7
        with:
          script: |
            const version = core.getInput('version', {required: true});
            const head    = `release/${version}`;                    // source branch
            const base    = context.payload.repository.default_branch; // target branch
            const title   = `Release ${version}`;
            const body    = `Automated PR: merge **${head}** into **${base}**`;

            // Check if branch exists; skip if it does not.
            try {
              await github.rest.repos.getBranch({
                owner: context.repo.owner,
                repo:  context.repo.repo,
                branch: head
              });
            } catch {
              core.setFailed(`Branch ${head} does not exist – aborting.`);
              return;
            }

            // Avoid duplicate PRs
            const {data: prs} = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              head:  `${context.repo.owner}:${head}`,
              base
            });
            if (prs.length) {
              core.info(`PR already exists: ${prs[0].html_url}`);
              return;
            }

            // Create the PR
            const {data: pr} = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              head,
              base,
              title,
              body
            });

            core.info(`Created PR ${pr.html_url}`);

            // Request reviewers (GitHub usernames, not emails)
            const reviewers = ['wildan3105']; // 👈 Customize this list
            if (reviewers.length > 0) {
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                reviewers: reviewers
              });
              core.info(`Requested review from: ${reviewers.join(', ')}`);
            }
        env:
          version: ${{ steps.vars.outputs.version }}
